services:
  ssh-chat:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "22:2222"
    volumes:
      - ./.container:/app/.keystore:rw
    entrypoint: ["/app/app"]
