services:
  ssh-chat:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "22:2222"
    volumes:
      - keystore-data:/app/.keystore
    entrypoint: ["/app/app"]

volumes:
  keystore-data:
    driver: local
